### ISSUE TITLE
Research on the Topic of Lags

### ISSUE THREAD

**Issue by zarahz** [micheltokic/stable_baselines_model_based_rl#2]
- Annahme 1:
Csv daten sind nicht vollständig: zB beim Cartpole fehlt in einem state ein Wert oder ist in einem falschen Format angegeben (string/hex/.. statt int) beispielsweise für die Position

- Annahme 2:
Csv daten sind verrauscht -> state ist stark abweichend von den letzten n lags (für alle state werte? pos., beschl., ...)
Problematik: sehr ungewiss, ob die Umgebung große Änderungen auslöst oder die Daten tatsächlich verrauscht sind

-> Möglicher Ansatz wäre eine Schätzung zu berechnen, indem zB der durchschnitt aus den n lags dafür eingesetzt wird
**Zu klären**: Sind die Lags auf ähnliche states bezogen oder schätzt man aus den letzten n states (n = lags)

Offizielle Beschreibung:

> Observations may be incomplete or noisy which means the true state of the environment is hidden. 
> Formally this Setup is called partially observable Markov decision process (POMDP) since agents act under uncertainty. ([source](https://people.csail.mit.edu/hasinoff/pubs/hasinoff-rlhidden-2002.pdf))
>

**Comment by marvinweber** [comment]
Lag bzw. Window_Size (vom LSTM Layer) wird mittlerweile unterstützt.
