### ISSUE TITLE
Data Normalization

### ISSUE THREAD

**Issue by JonasWild** [micheltokic/stable_baselines_model_based_rl#4]
Wenn beim Training die Daten normalisiert werden, dann muss sich das ja gemerkt werden für das Kapseln. Ansonsten sind die Inputs in einer anderen Skalierung. Verschiedene Normalisierungsmethoden in der config anbieten ? (Min-Max-Scaling, Standardization, etc.)

**Comment by marvinweber** [comment]
[Hier](https://github.com/micheltokic/stable_baselines_model_based_rl/blob/6d2908abdc9fb86eff7de0dac72e3138c5ba74f9/stable_baselines_model_based_rl/dynamic_model_trainer/model_builder.py#L34) und [hier](https://github.com/micheltokic/stable_baselines_model_based_rl/blob/6d2908abdc9fb86eff7de0dac72e3138c5ba74f9/stable_baselines_model_based_rl/dynamic_model_trainer/model_builder.py#L43) werden zwei Lambda Layers benutzt (und im Model gespeichert), um die Daten erst zu normalisieren und anschließend wieder auf die Ursprungsgrößen zurückzurechnen.
